{{- if .Values.quaiCicd.cloud }}
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  annotations:
  name: {{ include "quai-cicd.name" $ }}
  namespace: {{ .Values.quaiCicd.env }}
spec:
  healthCheck:
    checkIntervalSec: 15
    port: 50451
    requestPath: /healthz
    type: HTTP
{{- end }}