name: Common Build and Deploy to Sandbox
on:
  workflow_call:
    inputs:
      needs_build:
        description: 'Whether to build or not'
        required: true
        type: boolean
        default: false
      install_command:
        description: 'Command to run to install dependencies'
        type: string
        required: false
      cloud_deploy:
        required: true
        type: boolean
        default: false
      skip_deploy:
        required: false
        type: boolean
        default: false
      env:
        required: false
        type: string
        default: quai-sandbox
      build_command:
        description: 'Command to run to build'
        type: string
        required: false
      needs_docker:
          required: false
          type: boolean
          default: false
      include_chart:
          required: false
          type: boolean
          default: false
      update_version:
          required: false
          type: boolean
          default: true
    secrets:
      GH_PAT:
        description: 'needed for github login'
        required: true
      DOCKER:
        description: 'needed for registry login'
        required: false
      KUBE_CONFIG:
        description: 'needed for kube setup'
        required: false
      BUILD_ARGS:
        description: 'needed for build args'
        required: false
      DOCKER_BUILD_ARGS:
        description: 'needed for docker build args'
        required: false
jobs:
  detect-language:
    runs-on: ubuntu-latest
    outputs:
      language: ${{ env.detected-language }}

    steps:
      - uses: actions/checkout@v2

      - name: Detect Language
        id: set-language
        run: |
          if [[ -f "package.json" && ! -f "tsconfig.json" ]]; then
            echo "detected-language=javascript" >> $GITHUB_ENV
            echo "detected-language=javascript"
          elif [[ -f "tsconfig.json" ]]; then
            echo "detected-language=typescript" >> $GITHUB_ENV
          elif [[ -f "go.mod" ]]; then
            echo "detected-language=go" >> $GITHUB_ENV
          elif [[ -f "mix.exs" ]]; then
            echo "detected-language=elixir" >> $GITHUB_ENV
          else
            echo "detected-language=unknown" >> $GITHUB_ENV
          fi
          echo "testing"

  buildDeploySandboxJS:
    needs: detect-language
    if: github.event.pull_request.merged == true && needs.detect-language.outputs.language == 'javascript'
    uses: ./.github/workflows/build-deploy-js.yml
    secrets:
      DOCKER: ${{ secrets.DOCKER }}
      GH_PAT: ${{ secrets.GH_PAT }}
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      DOCKER_BUILD_ARGS: ${{ secrets.DOCKER_BUILD_ARGS }}
      BUILD_ARGS: ${{ secrets.BUILD_ARGS }}
    with:
      env: ${{ inputs.env }}
      update_version_command: npm version prerelease --preid=rc --no-git-tag-version
      rails: '[[ ! "$VERSION" =~ "pre" ]]'
      update_version: true
      cloud_deploy: ${{ inputs.cloud_deploy }}
      needs_build: ${{ inputs.needs_build }}
      install_command: ${{ inputs.install_command }}
      skip_deploy: ${{ inputs.skip_deploy }}

  buildDeploySandboxTS:
    needs: detect-language
    if: github.event.pull_request.merged == true && needs.detect-language.outputs.language == 'typescript'
    uses: ./.github/workflows/build-deploy-ts.yml
    secrets:
      DOCKER: ${{ secrets.DOCKER }}
      GH_PAT: ${{ secrets.GH_PAT }}
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      DOCKER_BUILD_ARGS: ${{ secrets.DOCKER_BUILD_ARGS }}
      BUILD_ARGS: ${{ secrets.BUILD_ARGS }}
    with:
      env: ${{ inputs.env }}
      update_version_command: npm version prerelease --preid=rc --no-git-tag-version
      rails: '[[ ! "$VERSION" =~ "pre" ]]'
      update_version: true
      cloud_deploy: ${{ inputs.cloud_deploy }}
      needs_build: ${{ inputs.needs_build }}
      install_command: ${{ inputs.install_command }}
      skip_deploy: ${{ inputs.skip_deploy }}

  buildDeploySandboxGo:
    needs: detect-language
    if: github.event.pull_request.merged == true && needs.detect-language.outputs.language == 'go'
    uses: ./.github/workflows/build-deploy-go.yml
    secrets:
      DOCKER: ${{ secrets.DOCKER }}
      GH_PAT: ${{ secrets.GH_PAT }}
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      DOCKER_BUILD_ARGS: ${{ secrets.DOCKER_BUILD_ARGS }}
      BUILD_ARGS: ${{ secrets.BUILD_ARGS }}
    with:
      env: ${{ inputs.env }}
      update_version_command: "echo \"v$(semver -i patch $(sed 's/^v//' VERSION))\" > VERSION"
      rails: '[[ ! "$VERSION" =~ "pre" ]]'
      update_version: ${{ inputs.update_version }}
      cloud_deploy: ${{ inputs.cloud_deploy }}
      needs_build: ${{ inputs.needs_build }}
      install_command: ${{ inputs.install_command }}
      skip_deploy: ${{ inputs.skip_deploy }}
      build_command: ${{ inputs.build_command }}
      needs_docker: ${{ inputs.needs_docker }}
      include_chart: ${{ inputs.include_chart }}
