name: Test Use of Common Patch Workflow
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to use'
        required: true
        default: 'main'
jobs:
  call-common-workflow:
    uses: dominant-strategies/quai-cicd/.github/workflows/deploy-sandbox-common.yml@main
    with:
      needs_build: true
      build_command: "npm run build"
      needs_docker: true
      include_chart: true
      cloud_deploy: true
      skip_deploy: false
      update_version: true
      env: "quai-sandbox"
      gcp_project_id: "flash-gasket-349320"
      token_secret_name: "gke-sandbox-token"
    secrets:
      DOCKER: ${{ secrets.DOCKER }}
      BUILD_ARGS: ''
      DOCKER_BUILD_ARGS: ''
      KUBE_CONFIG: ${{ secrets.KUBECONFIG_SANDBOX }}
      GH_PAT: ${{ secrets.GH_PAT }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY2 }}
      GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
      GH_GCP_TOKEN: ${{ secrets.GH_GCP_TOKEN }}
