name: Test Use of Common Cut Release Workflow
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to use'
        required: true
        default: 'main'
jobs:
  call-common-workflow:
    uses: dominant-strategies/quai-cicd/.github/workflows/cut-release-common.yml@main
    with:
      branch: main
      needs_build: true
      build_command: "make go-quai"
      needs_docker: false
      include_chart: false
      cloud_deploy: false
      skip_deploy: true
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
