name: Test Use of Common Build on PR
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - 'v?[0-9]+.[0-9]+'
jobs:
  call-common-workflow:
    uses: dominant-strategies/quai-cicd/.github/workflows/deploy-sandbox-common.yml@main
    with:
      needs_build: true
      build_command: "make go-quai"
      needs_docker: false
      include_chart: false
      cloud_deploy: false
      skip_deploy: true
      update_version: false
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
