name: Test Use of Common Dev Workflow
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to use'
        required: true
        default: 'main'
jobs:
  call-common-workflow:
    uses: dominant-strategies/quai-cicd/.github/workflows/deploy-dev-common.yml@main
    with:
      needs_build: true
      build_command: "npm run build"
      needs_docker: false
      include_chart: false
      cloud_deploy: false
      skip_deploy: true
      update_version: false

    secrets:
      DOCKER: ${{ secrets.DOCKER }}
      BUILD_ARGS: ''
      DOCKER_BUILD_ARGS: ''
      GH_PAT: ${{ secrets.GH_PAT }}
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY2 }}
      GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
      GH_GCP_TOKEN: ${{ secrets.GH_GCP_TOKEN }}

